### ISSUE TITLE
Unable to spawn the robot

### ISSUE THREAD

**Issue by inessousacaldas** [ee09115/conde_simulator#1]
I spawn the world and then when I try to launch the spwan_robot or any file that spawn models it gives me an error: "Service call failed: transport error completing service call: unable to receive data from sender, check sender's logs for details"
Do you know how to solve this? Thank you.
I'm using ROS Kinetic with Gazebo 7.14 on Ubuntu 16.04.

**Comment by ee09115** [comment]
I am using ROS Kinetic with Gazebo 7.0.0 on Ubuntu 16.04 and I have no problem in spawning the robot or the world. Did you perform the full installation of ROS Kinetic?
Can you provide me the list of steps you followed to run the simulator?

Valter

**Comment by inessousacaldas** [comment]
I perform the installation has it described in the link you provide, that comes with Gazebo in the version I mentioned. In a catkin workspace I build the package and I launch the world with spawn_world.launch. Then I try to spawn the robot with the spawn_robot.launch but it gives me the error above and in the terminal window with the world appears segmentation fault.

**Comment by ee09115** [comment]
Please share with me a print-screen of the output in the terminal when you try to spawn the robot.

**Comment by inessousacaldas** [comment]
![spawn_robot](https://user-images.githubusercontent.com/14773801/48027650-40239e00-e141-11e8-84df-80fdd7e8b2a5.png)

**Comment by ee09115** [comment]
Please check if you have the models directory in the following path:~/home/<your_user>/.gazebo/
See the issues in this page (at the bottom of the page): https://bitbucket.org/ee09115/conde_simulator_student/src/default/

**Comment by ee09115** [comment]
By the way, are you using a virtual machine with ubuntu?

**Comment by inessousacaldas** [comment]
I had already tried that fix before talking to you. No I'm not using a virtual machine with Ubuntu.
I'm trying to spawn a very simple robot in a empty world, following a Gazebo tutorial and it gives me the same error.

**Comment by ee09115** [comment]
It seems that something went wrong during the ROS installation or the configuration of your graphics driver.
What graphics card do you have?

**Comment by inessousacaldas** [comment]
I have a Nvidia GeForce GTX 970M.

**Comment by ee09115** [comment]
Search for "Additional Drivers" in your OS and check if you are using the NVIDIA driver.

**Comment by inessousacaldas** [comment]
![driver](https://user-images.githubusercontent.com/14773801/48061511-1dcc6780-e1b7-11e8-8e09-a251edd3e93f.png)

**Comment by ee09115** [comment]
Try change it for the for the 396.54 or 410.73 version, reboot your pc and see if it worked.

**Comment by inessousacaldas** [comment]
I tried with both versions and still didn't work. I setup a new clean environment and install everything again and I managed to get it to work. I still don't know what the problem was, but thank you so much for your help and quick replies.

**Comment by ee09115** [comment]
Uninstall/purge ROS and setup a clean installation was my last guess (as presented [here](https://rethinkrobotics.interaforum.com/topic/652-gazebo-simulation-not-running/)). 
You're welcome. I am closing this issue.
