### ISSUE TITLE
Calculating IPM

### ISSUE THREAD

**Issue by inessousacaldas** [ee09115/conde_simulator#2]
Hello, 

I'm trying to calculate the IPM for the right and left images following this example: http://answers.opencv.org/question/174548/inverse-perspective-mapping-ipm-on-the-capture-from-camera-feed/

I'm assuming that the transformation matrices are cameraRight_T_chess_robot, cameraRight_T_cam_chess and the equivalent for the left camera, however after the transformations the resulting images are black. Could you give me some pointers to estimate the IPM? 

Thank you

**Comment by ee09115** [comment]
Hello,

if you want to perform the IPM transformation, you should take a look at the this [article](https://www.researchgate.net/publication/323423499_Design_of_an_Embedded_Multi-Camera_Vision_System-A_Case_Study_in_Mobile_Robotics) (pages 5 to 7).
It describes the necessary steps to map the input image into the "birds eye view" you are trying to achieve.

Good luck,
